baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Allan Chen'
theme = 'PaperMod'


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    weight = 1

    [[menu.main]]
    parent = "about"
    name = "Hello World"
    url = "/about/hello-world/"
    weight = 2